version: '3.8'
services:
  biblioplexo:
    build: .
    container_name: biblioplexo
    ports:
      - "8080:80"
    volumes:
      - .:/usr/share/nginx/html
    restart: unless-stopped      
    networks:
    - proxy

networks:
    proxy:
        external: true